// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.20.3
// source: pkg/api/userservice/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 健康检查
type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_userservice_v1_user_proto_rawDescGZIP(), []int{0}
}

type HealthzReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzReply) Reset() {
	*x = HealthzReply{}
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzReply) ProtoMessage() {}

func (x *HealthzReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzReply.ProtoReflect.Descriptor instead.
func (*HealthzReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_userservice_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *HealthzReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 创建用户（占位）
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_userservice_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReply) Reset() {
	*x = CreateUserReply{}
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReply) ProtoMessage() {}

func (x *CreateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReply.ProtoReflect.Descriptor instead.
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_userservice_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 登录（占位）
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_userservice_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_userservice_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_userservice_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_pkg_api_userservice_v1_user_proto protoreflect.FileDescriptor

const file_pkg_api_userservice_v1_user_proto_rawDesc = "" +
	"\n" +
	"!pkg/api/userservice/v1/user.proto\x12\x0euserservice.v1\x1a\x1cgoogle/api/annotations.proto\"\x10\n" +
	"\x0eHealthzRequest\"&\n" +
	"\fHealthzReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"K\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\x0fCreateUserReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"N\n" +
	"\n" +
	"LoginReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn2\xa9\x02\n" +
	"\vUserService\x12Y\n" +
	"\aHealthz\x12\x1e.userservice.v1.HealthzRequest\x1a\x1c.userservice.v1.HealthzReply\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthz\x12f\n" +
	"\n" +
	"CreateUser\x12!.userservice.v1.CreateUserRequest\x1a\x1f.userservice.v1.CreateUserReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12W\n" +
	"\x05Login\x12\x1c.userservice.v1.LoginRequest\x1a\x1a.userservice.v1.LoginReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/loginB<Z:github.com/ArthurWang23/miniblog/pkg/api/userservice/v1;v1b\x06proto3"

var (
	file_pkg_api_userservice_v1_user_proto_rawDescOnce sync.Once
	file_pkg_api_userservice_v1_user_proto_rawDescData []byte
)

func file_pkg_api_userservice_v1_user_proto_rawDescGZIP() []byte {
	file_pkg_api_userservice_v1_user_proto_rawDescOnce.Do(func() {
		file_pkg_api_userservice_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_userservice_v1_user_proto_rawDesc), len(file_pkg_api_userservice_v1_user_proto_rawDesc)))
	})
	return file_pkg_api_userservice_v1_user_proto_rawDescData
}

var file_pkg_api_userservice_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_api_userservice_v1_user_proto_goTypes = []any{
	(*HealthzRequest)(nil),    // 0: userservice.v1.HealthzRequest
	(*HealthzReply)(nil),      // 1: userservice.v1.HealthzReply
	(*CreateUserRequest)(nil), // 2: userservice.v1.CreateUserRequest
	(*CreateUserReply)(nil),   // 3: userservice.v1.CreateUserReply
	(*LoginRequest)(nil),      // 4: userservice.v1.LoginRequest
	(*LoginReply)(nil),        // 5: userservice.v1.LoginReply
}
var file_pkg_api_userservice_v1_user_proto_depIdxs = []int32{
	0, // 0: userservice.v1.UserService.Healthz:input_type -> userservice.v1.HealthzRequest
	2, // 1: userservice.v1.UserService.CreateUser:input_type -> userservice.v1.CreateUserRequest
	4, // 2: userservice.v1.UserService.Login:input_type -> userservice.v1.LoginRequest
	1, // 3: userservice.v1.UserService.Healthz:output_type -> userservice.v1.HealthzReply
	3, // 4: userservice.v1.UserService.CreateUser:output_type -> userservice.v1.CreateUserReply
	5, // 5: userservice.v1.UserService.Login:output_type -> userservice.v1.LoginReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_userservice_v1_user_proto_init() }
func file_pkg_api_userservice_v1_user_proto_init() {
	if File_pkg_api_userservice_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_userservice_v1_user_proto_rawDesc), len(file_pkg_api_userservice_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_userservice_v1_user_proto_goTypes,
		DependencyIndexes: file_pkg_api_userservice_v1_user_proto_depIdxs,
		MessageInfos:      file_pkg_api_userservice_v1_user_proto_msgTypes,
	}.Build()
	File_pkg_api_userservice_v1_user_proto = out.File
	file_pkg_api_userservice_v1_user_proto_goTypes = nil
	file_pkg_api_userservice_v1_user_proto_depIdxs = nil
}
